### ISSUE TITLE
Python begginer question: 'Function to show muttability'

### ISSUE THREAD

**Issue by surister** [bregman-arie/devops-interview-questions#12]
Interview question: **What function can you use to show that a certain data type is mutable?**

The given answer is: **The id function can be used to check if a given variable is mutable or not.**

... How? The [id](https://docs.python.org/3/library/functions.html#id) function basically returns the memory address of the object, so, how can we tell whether an object is mutable or not by using id()?

Let's define immutability.

[immutable](https://docs.python.org/3/glossary.html#immutable)

> An object with a fixed value. Immutable objects include numbers, strings and tuples. Such an object cannot be altered. A new object has to be created if a different value has to be stored. They play an important role in places where a constant hash value is needed, for example as a key in a dictionary.
### Builtin objects.

**Mutable**: list, dict ...

**Immutable**: int, float, str, tuple...

Only immutable objects can be used as dictionaries keys, in order to compare the keys, the objects are hashed and compared, could we say that hashable objects are inmutable?

Most of Python’s immutable built-in objects are hashable; mutable containers (such as lists or dictionaries) are not; immutable containers (such as tuples and frozensets) are only hashable if their elements are hashable. Objects which are instances of user-defined classes are hashable by default. They all compare unequal (except with themselves), and their hash value is derived from their id().

Looks like yes, hashable objects are immutable but...

[Python data model](https://docs.python.org/3/reference/datamodel.html#objects-values-and-types)
> 
> The value of some objects can change. Objects whose value can change are said to be mutable; objects whose value is unchangeable once they are created are called immutable. (The value of an immutable container object that contains a reference to a mutable object can change when the latter’s value is changed; however the container is still considered immutable, because the collection of objects it contains cannot be changed. So, immutability is not strictly the same as having an unchangeable value, it is more subtle.) 
**> An object’s mutability is determined by its type; for instance, numbers, strings and tuples are immutable, while dictionaries and lists are mutable.**

So, a given object is inmutable if it can be hashed. Well, it is not always true. You can still have a user defined class that is hashable and mutable by modifying `__hash__ and __eq__`

**Proposed answe**r: 'You can usually use the function hash() to check an object mutability, if it is
hashable it is immutable, although this does not always work as intended as user defined objects might be mutable and hashable'

**Comment by surister** [comment]
I do not agree.
Id(x) -> int
This is an integer which is guaranteed to be unique and constant for this object during its lifetime. Two objects with non-overlapping lifetimes may have the same id() value.

Doesn't really have to be with mutability/immutability.

Actually your example says nothing.

You show the id of 5 and then the id of 7 and for some reason it's weird that they are different?
```
>>> x = 5
>>> id(x)
140101294117984
>>> id(5)
140101294117984
>>> x = x + 2
>>> x
7
>>> id(x)
140101294118048
>>> id(7)
140101294118048
>>> id(5)
140101294117984
>>> 

```
Immutable object have the same behavior, what sense does it make to change the C address? is
140101294117984 more privileged than 140101294118048?
```
>>> a = [1, 2, 3]
>>> a
[1, 2, 3]
>>> id(a)
140101285349328
>>> a.append((1,2, 3))
>>> a
[1, 2, 3, (1, 2, 3)]
>>> id(a)
140101285349328
>>> 
 ```

As for othis, I still fail to understand how do you use id to test whether an object is immutable or not. With hash(x) on the other hand, if we obvious user defined classes, we know that there is a stron relation between mutability and hashing.
```
>>> hash(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
>>> 
```
We can assert for sure that the variable a is mutable as it cannot be hashed.

**Comment by bregman-arie** [comment]
I don't argue with you about hash(x), it's a great way. Thanks for mentioning it. It's good to learn new things. But I still would like to understand why id isn't good enough. Your examples didn't prove it can't be used. they showed (once again) that changes to immutable types, will change the memory address for the variable while changes to mutable type will keep the id the same as before the change.

I understand that in your example it's simply gave to each value a different address and yet when checking the id of the variable (x) the id changed in case of the integers hence, a user can define the simple rule of "if changing the variable, didn't change the id, then the data type of the variable is mutable. otherwise, it's immutable", no? is there an example that can show it doesn't work?

**Comment by surister** [comment]
>  that changes to immutable types, will change the memory address for the variable
No, we only changed the name references and in both cases, mutable and immutable the address are the **same**

"if changing the variable, didn't change the id, then the data type of the variable is mutable. otherwise, it's immutable"

Again, object address doesn't have anything to be with mutability, there is a difference between changing the name reference and the object that it is stored in the memory instead. As shown in my examples, the id are constants regardless of the mutability of the object.

> 
 Is there an example that can show it doesn't work?


Is there an example that it works?

I will just follow the your very same example:

```
>>> x = [5]
>>> id(x)
140006458386384
>>> x = x + [3]
>>> id(x)
140006457253632
>>> type(x)
<class 'list'>
>>> 
>>> 
# Your snippet
x = 5
id(x)
140346832667744
x = x + 2
id(x)
140346832667808
```
We are just doing the same thing and obtaining the same result, two different id address,  we didn't modify the address but the references, pointing now to different places.

**Comment by bregman-arie** [comment]
Very good. Thank you for your patience and for this great lesson.
I will change the answer :)

**Comment by bregman-arie** [comment]
Fixed.

**Comment by haiya512** [comment]
> > that changes to immutable types, will change the memory address for the variable
> > No, we only changed the name references and in both cases, mutable and immutable the address are the **same**
> 
> "if changing the variable, didn't change the id, then the data type of the variable is mutable. otherwise, it's immutable"
> 
> Again, object address doesn't have anything to be with mutability, there is a difference between changing the name reference and the object that it is stored in the memory instead. As shown in my examples, the id are constants regardless of the mutability of the object.
> 
> > 
> 
> Is there an example that can show it doesn't work?
> 
> Is there an example that it works?
> 
> I will just follow the your very same example:
> 
> ```
> >>> x = [5]
> >>> id(x)
> 140006458386384
> >>> x = x + [3]
> >>> id(x)
> 140006457253632
> >>> type(x)
> <class 'list'>
> >>> 
> >>> 
> # Your snippet
> x = 5
> id(x)
> 140346832667744
> x = x + 2
> id(x)
> 140346832667808
> ```
> 
> We are just doing the same thing and obtaining the same result, two different id address, we didn't modify the address but the references, pointing now to different places.

i do not really understand your example, but when i do a try, with python 3.7 on my win10
the result is:
`Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> x = [5]
>>> id(x)
2432450143240
>>> x += [3]
>>> id(x)
2432450143240
>>> x
[5, 3]`

**Comment by surister** [comment]
You get the same id because you are using `+=` which suggarcoats the `__iadd__` method. 
It is different from `a = a + x` they have slightly differente behaviours.

```
# WITHOUT __iadd__
>>> a = [5]
>>> id(5)
3031317965232
>>> a = a + [5]
>>> id(a)
3031319329536
>>> a
[5, 5]

# With __iadd__
>>> b = [5]
>>> id(b)
3031319046528
>>> b += [5]
>>> id(b)
3031319046528
>>> b
[5, 5]
>>>
```

If you disassemble both snippets you will see that one uses `BINARY_ADD` and the other `INPLACE_ADD`

`a = a + x`
```
  2           0 LOAD_CONST               0 (5)
              2 BUILD_LIST               1
              4 STORE_NAME               0 (a)

  4           6 LOAD_NAME                0 (a)
              8 LOAD_CONST               1 (3)
             10 BUILD_LIST               1
             12 BINARY_ADD
             14 STORE_NAME               0 (a)
             16 LOAD_CONST               2 (None)
             18 RETURN_VALUE
```
`a += x`

```
 3           0 LOAD_CONST               0 (3)
              2 BUILD_LIST               1
              4 STORE_NAME               0 (b)

  5           6 LOAD_NAME                0 (b)
              8 LOAD_CONST               1 (2)
             10 BUILD_LIST               1
             12 INPLACE_ADD
             14 STORE_NAME               0 (b)
             16 LOAD_CONST               2 (None)
             18 RETURN_VALUE 
```

The second is used to modify mutable objects and the other for unmutable objects.

You can read more about this in: https://stackoverflow.com/questions/15376509/when-is-i-x-different-from-i-i-x-in-python

**Comment by haiya512** [comment]
thank you for your answer
