### ISSUE TITLE
Suggestion: Add number of answered questions.

### ISSUE THREAD

**Issue by surister** [bregman-arie/devops-interview-questions#50]
In the head of the README.md we can read:

📊  There are currently 551 questions

My suggestion is to add the number of answered questions as well in a format somewhat like this:

📊  There are currently 551 questions - 349 are answered, why don't you help us to expand this number? [link to contributing.md]

**Comment by bregman-arie** [comment]
Sound good :) Since you are a collaborator now, go for it :)

**Comment by surister** [comment]
I will get into it, quick question though, why +8?
file: /scripts/count_questions.sh
```
#!/bin/bash
echo $((8 + $(cat README.md | grep \<\/summary\> | wc -l)))
```

**Comment by bregman-arie** [comment]
because of the 8 scenario questions (they have different format). We need to replace it with something more dynamic :)

**Comment by surister** [comment]
> 
> 
> because of the 8 scenario questions (they have different format). We need to replace it with something more dynamic :)

A posible answer could be:

`echo $(( $(ls .scenarios/ | grep .*md | wc -l) + $grep \<\/summary\> README.md | wc -l) ))`

![imagen](https://user-images.githubusercontent.com/37985796/70224115-fbf03c00-174c-11ea-99d8-507d2b0a7c2b.png)

Will always work as long as we have 1 question per .md file.

**Comment by bregman-arie** [comment]
Good idea. I'm fine with keeping 1 question/scenario per .md file
